container:
  image: node:12
  cpu: 8
  memory: 8G
  use_static_ip: "true"

testServer_task:
  timeout_in: 120
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
    populate_script: npm ci
  ip_script: wget -qO- ifconfig.co
  installPackages: npm i ncp@^2.0.0
  installDevPackages: npm i --save-dev q@^1.5.1  screeps@4.2.14 dotenv@^16.0.1 screeps-api@1.16.0 screepsmod-admin-utils@1.28.1 screepsmod-auth@2.6.2",
  testServer_script: npm run test-server
