version: '3'
services:
    screeps:
        image: screepers/screeps-launcher
        volumes:
            - ./config.yml:/screeps/config.yml
            - ./dist:/screeps/dist
            - screeps-data:/screeps
        ports:
            - 21025-21026:21025-21026
        restart: unless-stopped
volumes:
    screeps-data:
